Update rankit-multiaz-cicd.yml

diff --git a/.github/workflows/rankit-multiaz-cicd.yml b/.github/workflows/rankit-multiaz-cicd.yml
--- a/.github/workflows/rankit-multiaz-cicd.yml
+++ b/.github/workflows/rankit-multiaz-cicd.yml
@@ -22,7 +22,7 @@ jobs:
 
       # 2. Gradle 설정
       - name: Setup Gradle
-        uses: gradle/actions/setup-gradle@v3.1.0
+        uses: gradle/actions/setup-gradle@v417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0
 
       # 3. Jar 파일 빌드 (테스트 제외)
       - name: Build with Gradle Wrapper
@@ -54,15 +54,12 @@ jobs:
     steps:
       # 1. AWS CLI 설치
       - name: Install AWS CLI
-        id: install-aws-cli
         run: |
           sudo apt-get update
           sudo apt-get install awscli -y
 
       # 2. AWS 자격 증명 설정
       - name: Configure AWS credentials
-        id: configure-aws
-        needs: install-aws-cli
         env:
           AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
           AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
@@ -73,8 +70,7 @@ jobs:
           
       # 3. EC2 인스턴스 대상 등록 해제 (EC2-A)
       - name: Deregister EC2-A from Target Group
-        id: deregister-ec2-a
-        needs: configure-aws
+        needs: Configure AWS credentials
         run: |
           aws elbv2 deregister-targets \
             --target-group-arn ${{ secrets.TARGET_GROUP_ARN }} \
@@ -82,8 +78,7 @@ jobs:
       
       # 4. EC2-A에 Docker 컨테이너 배포
       - name: Deploy to EC2-A via SSM
-        id: deploy-ec2-a
-        needs: deregister-ec2-a
+        needs: Deregister EC2-A from Target Group
         run: |
           aws ssm send-command \
             --instance-ids "${{ secrets.EC2_A_ID }}" \
@@ -92,29 +87,28 @@ jobs:
             --comment "Deploying application to EC2-A"
       
       # 5. EC2-A에서 헬스체크 수행
-      - name: Perform health check on EC-A
+      - name: Perform health check on EC2-A
         id: healthcheck-ec2-a
-        needs: deploy-ec2-a
+        needs: Deploy to EC2-A via SSM
         run: |
           RESULT=$(aws ssm send-command \
             --instance-ids "${{ secrets.EC2_A_ID }}" \
             --document-name "AWS-RunShellScript" \
-            --parameters '{"commands":["curl -f http://localhost:8080/ || echo \"Health check failed on EC-A\""]}' \
-            --comment "Performing health check on EC-A" \
+            --parameters '{"commands":["curl -f http://localhost:8080/ || echo \"Health check failed on EC2-A\""]}' \
+            --comment "Performing health check on EC2-A" \
             --query "Command.CommandId" \
             --output text)
           sleep 10  # 헬스 체크 결과를 기다리기 위해 대기
           OUTPUT=$(aws ssm list-command-invocations --command-id $RESULT --details --output json)
           # 헬스 체크 실패 여부 확인
           if echo "$OUTPUT" | grep -q "Health check failed"; then
-            echo "Health check failed on EC-A"
+            echo "Health check failed on EC2-A"
             exit 1  # 파이프라인 종료
           fi
 
       # 6. EC2 인스턴스 대상 재등록 (EC2-A)
-      - name: Register EC-A to Target Group
-        id: register-ec2-a
-        needs: healthcheck-ec2-a
+      - name: Register EC2-A to Target Group
+        needs: Perform health check on EC2-A
         run: |
           aws elbv2 register-targets \
             --target-group-arn ${{ secrets.TARGET_GROUP_ARN }} \
@@ -122,28 +116,25 @@ jobs:
       
       # 7. EC2 인스턴스 대상 등록 해제 (EC2-C)
       - name: Deregister EC-C from Target Group
-        id: deregister-ec2-c
-        needs: register-ec2-a
+        needs: Register EC2-A to Target Group
         run: |
           aws elbv2 deregister-targets \
             --target-group-arn ${{ secrets.TARGET_GROUP_ARN }} \
             --targets Id=${{ secrets.EC2_C_ID }}
 
       # 8. EC2-C에 Docker 컨테이너 배포
-      - name: Deploy to EC-C via SSM
-        id: deploy-ec2-c
-        needs: deregister-ec-c
+      - name: Deploy to EC2-C via SSM
+        needs: Deregister EC-C from Target Group
         run: |
           aws ssm send-command \
             --instance-ids "${{ secrets.EC2_C_ID }}" \
             --document-name "AWS-RunShellScript" \
             --parameters '{"commands":["if [ $(docker ps -q -f \"ancestor='${{ secrets.DOCKER_USERNAME }}/rankitrun-be:latest'\" -f \"status=running\") ]; then docker stop $(docker ps -q -f \"ancestor='${{ secrets.DOCKER_USERNAME }}/rankitrun-be:latest'\"); fi && docker pull '${{ secrets.DOCKER_USERNAME }}/rankitrun-be:latest' && cd /home/ec2-user && docker-compose -f docker-compose.yml up -d"]}' \
-            --comment "Deploying application to EC-C"
+            --comment "Deploying application to EC2-C"
 
       # 9. EC2-C에서 헬스체크 수행
       - name: Perform health check on EC-C
-        id: healthcheck-ec2-c
-        needs: deploy-ec2-c
+        needs: Deploy to EC2-C via SSM
         run: |
           RESULT=$(aws ssm send-command \
             --instance-ids "${{ secrets.EC2_C_ID }}" \
@@ -162,8 +153,7 @@ jobs:
 
       # 10. EC2 인스턴스 대상 재등록 (EC-C)
       - name: Register EC-C to Target Group
-        id: register-ec2-c
-        needs: healthcheck-ec2-c
+        needs: Perform health check on EC-C
         run: |
           aws elbv2 register-targets \
             --target-group-arn ${{ secrets.TARGET_GROUP_ARN }} \
